### ISSUE TITLE
运行java脚本的时候报错

### ISSUE THREAD

**Issue by loneyao** [macacajs/wd.java#14]
clydeiMac:~ cly$ macaca server

> > webdriver sdk launched

  TypeError: this.device.getLogDir is not a function
      at XCTest.startSimLog (/usr/local/lib/node_modules/macaca-ios/node_modules/xctest-client/lib/xctest-client.js:64:43)
      at next (native)
      at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
      at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
      at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
      at Object.toPromise (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:118:63)
      at next (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:99:29)
      at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:69:7)

  TypeError: this.device.getLogDir is not a function
      at XCTest.startSimLog (/usr/local/lib/node_modules/macaca-ios/node_modules/xctest-client/lib/xctest-client.js:64:43)
      at next (native)
      at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
      at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
      at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
      at Object.toPromise (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:118:63)
      at next (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:99:29)
      at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:69:7)

**Comment by kobe990** [comment]
日志就这一个错吗？跑官方脚本用例也是这样吗？

**Comment by ziczhu** [comment]
@lengyao88 是真机还是模拟器，desired_caps 里面是怎么写的。
