### ISSUE TITLE
获取控件属性报错，求解决！

### ISSUE THREAD

**Issue by dsq3389** [macacajs/wd.java#5]
问题描述： 需要获取手势密码绘制区域的坐标，看到API有getAttribute这个方法，想通过这个方法获取控件的bounds，代码如下

String s=driver.elementById("pv_lock").getAttribute("bounds")
运行报错，日志如下：
recive: {"cmd":"find","args":{"strategy":"id","selector":"pv_lock","multiple":false}}

return: {"success":true,"data":{"ELEMENT":"1"}}

  NotImplementedError: The method is not implemented yet.
      at Object.module.exports.throw (/usr/local/lib/node_modules/macaca-cli/node_modules/koa/lib/context.js:91:23)
      at Object.module.exports (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/responseHandler.js:75:17)
      at throw (native)
      at onRejected (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:81:24)
      at runMicrotasksCallback (internal/process/next_tick.js:58:5)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
@xudafeng

**Comment by xudafeng** [comment]
@dsq3389 先用 getWindowSize

**Comment by xudafeng** [comment]
@dsq3389  可以获取 size 和 origin
